import { StyleSheet } from "react-native";
import Color from "../../Constant/Color";
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    marginTop: 36,
  },
  header: {
    backgroundColor: Color.colorPrimaryLight,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    padding: 8,
    paddingHorizontal: 12,
  },
  backBtnText: {
    color: "white",
    fontSize: 18,
  },
  headerTitle: {
    color: "white",
    fontSize: 18,
    marginLeft: 24,
  },
  content: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
  },
  bottom: {
    width: "100%",
    minHeight: 100,
    marginBottom: 50,
    backgroundColor: "white",
    borderStyle: "solid",
    borderWidth: 1,
    borderColor: "#ccc",
    display: "flex",
    flexDirection: "column",
  },
  voucherWrapper: {
    flex: 1,
    padding: 8,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    borderStyle: "solid",
    borderWidth: 1,
    borderColor: "transparent",
    borderBottomColor: "#ccc",
  },
  voucherTitle: {
    color: "black",
    fontSize: 16,
    marginLeft: 12,
  },
  voucherContent: {
    color: "#333",
    fontSize: 16,
    marginRight: 8,
  },
  invalidVoucherWrapper: {
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "red",
    padding: 4,
    paddingHorizontal: 8,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
  },
  invalidVoucherContent: {
    color: "red",
    fontSize: 13,
    marginRight: 8,
  },
  validVoucherWrapper: {
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "green",
    padding: 4,
    paddingHorizontal: 8,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
  },
  validVoucherContent: {
    color: "green",
    fontSize: 13,
    marginRight: 8,
  },
  moneyWrapper: {
    flex: 1,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    padding: 8,
  },
  money: {
    flex: 4,
    color: "black",
    fontSize: 16,
  },
  payBtn: {
    flex: 2,
    backgroundColor: Color.colorPrimary,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: 8,
    borderRadius: 20,
  },
  payBtnText: {
    color: "white",
  },
  emptyCartWrapper: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 24,
  },
  emptyCartText: {
    fontSize: 18,
    fontStyle: "italic",
    color: Color.colorPrimary,
  },
  emptyCartImg: {
    marginTop: 100,
  },
});
