import { StyleSheet } from "react-native";
import Color from "../../../Constant/Color";
import { Styles } from "../../../Constant/Styles";
export const styles = StyleSheet.create({
  textNormal: {
    color: "black",
    fontSize: 14,
  },
  textLarge: {
    color: "black",
    fontSize: 18,
  },
  flexCenter: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  container: {
    marginTop: 32,
    flex: 1,
    backgroundColor: Color.colorGray,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  backWrapper: {
    padding: 8,
    width: "100%",
    backgroundColor: "white",
    borderStyle: "solid",
    borderBottomColor: Color.colorLightGray,
    borderBottomWidth: 1,
  },
  starWrapper:{
    position: 'absolute',
    bottom: 10,
    left: 120,
    width: '100%',
    marginVertical: 4,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center'
  },
  productHeaderWrapper: {
    width: "100%",
    backgroundColor: "white",
    padding: 8,
  },
  blinkSaleImg: {
    position: "absolute",
    width: 120,
    resizeMode: "contain",
    top: -100,
    left: 20,
    zIndex: 10,
  },
  fewQuantityText:{
    position: 'absolute',
    bottom: 6,
    right: 0,
    color: 'white',
    fontSize: 14,
    backgroundColor: Color.colorOrange,
    padding: 6,
    borderRadius: 4,
  },  
  productImgWrapper: {
    width: "100%",
    height: 480,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    paddingVertical: 12,
  },
  productImg: {
    width: "100%",
    height: "100%",
    resizeMode: "contain",
  },
  productExpiry: {
    position: "absolute",
    bottom: 10,
    left: 0,
    backgroundColor: Color.colorDarkGray,
    color: "white",
    borderRadius: 4,
    padding: 4,
  },
  productName: {
    width: "100%",
    padding: 8,
    backgroundColor: "white",
    color: "black",
    fontSize: 16,
    fontWeight: "bold",
  },
  option: {
    marginTop: 12,
    padding: 8,
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  price: {
    flex: 1,
  },
  priceText: {
    fontSize: 18,
    color: "black",
    fontWeight: "bold",
  },
  originPriceText: {
    fontSize: 18,
    color: Color.colorGrayText,
    textDecorationLine: "line-through",
  },
  buyWrapper: {
    flex: 1,
    display: "flex",
    flexDirection: "row-reverse",
    position: "relative",
  },
  blinkStar: {
    position: "absolute",
    right: 0,
    top: -100,
  },
  quantity: {
    width: 240,
    height: 48,
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  btnQuantityAdj: {
    flex: 1,
    height: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: Color.colorPrimaryButton,
    borderStyle: "solid",
    borderWidth: 1,
    borderColor: Color.colorPrimary,
  },
  quantityText: {
    flex: 1,
    height: "100%",
    lineHeight: 48,
    textAlign: "center",
    fontSize: 20,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "white",
    borderTopColor: Color.colorPrimary,
    borderBottomColor: Color.colorPrimary,
  },
  productBuyBtn: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    width: 240,
    height: 48,
    borderRadius: 4,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: Color.colorPrimary,
  },
  outOfStock: {
    borderColor: Color.colorLightGray,
  },
  outOfStockText: {
    color: Color.colorGrayText,
  },
  productBuyBtnDisable: {
    opacity: 0.2,
  },
  productBuyText: {
    color: Color.colorPrimary,
    textAlign: "center",
    lineHeight: 48,
    fontSize: 20,
    marginRight: 12,
  },
  hidden: {
    display: "none",
  },
  productInfoWrapper: {
    marginTop: 12,
    backgroundColor: "white",
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  productInfoTitle: {
    marginBottom: 12,
  },
  productInfoContent: {
    marginBottom: 12,
  },
  productInfoTable: {
    borderStyle: "solid",
    borderColor: Color.colorDarkGray,
    borderWidth: 1,
    borderRadius: 4,
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
  },
  productInfoItemTitle: {
    width: "30%",
    backgroundColor: Color.colorLightGray,
    justifyContent: "flex-start",
    borderStyle: "solid",
    borderWidth: 1,
    borderColor: "transparent",
    borderBottomColor: Color.colorDarkGray,
  },
  productInfoItemContext: {
    width: "70%",
    padding: 8,
    borderStyle: "solid",
    borderWidth: 1,
    borderColor: "transparent",
    borderBottomColor: Color.colorGray,
  },
  commentWrapper: {
    backgroundColor: "white",
    marginTop: 12,
    width: "100%",
    display: "flex",
    padding: 8,
  },
  commentInput: {
    borderWidth: 1,
    borderColor: Color.colorLightGray,
    borderStyle: "solid",
    borderRadius: 4,
    height: 120,
    textAlignVertical: "top",
    marginTop: 8,
    padding: 4,
  },
  postCommentBtn: {
    width: "100%",
    padding: 12,
    borderRadius: 4,
    backgroundColor: Color.colorPrimaryLight,
    ...Styles.flexCenter,
    marginVertical: 4,
  },
  postCommentBtnTxt: {
    color: "white",
    fontSize: 15,
  },
  myRateWrapper: {},
  rateWrapper: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    marginTop: 12,
  },
  rateText: {
    ...Styles.GrayNormalText,
    marginRight: 12,
  },
});
